### ISSUE TITLE
Remove process_folder function?

### ISSUE THREAD

**Issue by mrghg** [hugs-cloud/hugs#2]
Currently, process_folder assumes only one site per folder. May not always be the case, and (I think) will cause processing to do something weird (haven't tested, as I don't want to screw up my objects store!).

It's also a bit clunky having the GC precisions hard-wired in here, as it's particular to the current GCWerks output format.

Since this is just a wrapper to process_files, as an alternative, I suggest users have to pre-prepare the inputs to process_files.

**Comment by gareth-j** [comment]
`process_folder` has been removed in 0aed3d82dd2b2608363bbfae6b96aa77947b31dd.
