### ISSUE TITLE
Remove ValueError when no instrument is specified in GC filename?

### ISSUE THREAD

**Issue by mrghg** [hugs-cloud/hugs#3]
Currently, a ValueError is raised when processing GCWerks .C files, if there's no instrument specified in the filename. E.g. macehead.00.C (rather than, for example, macehead-medusa.00.C). These filenames are only used for the GCMD, so I think it should be fine to default to GCMD, if this is the format of the filename.

**Comment by gareth-j** [comment]
Now defaults to GCMD.
